[base]
language = "en"

[preprocessing]
enabled = false
doc_type = "csv"

[preprocessing.extra]
id_column = "id"
text_column = "body"
timestamp_column = "timestamp"

[docprocessing]
enabled = true
batch_size = 50
prefer_gpu_for_coref = true
n_process = 1

[corpusprocessing]
enabled = true