[base]
language = "en"

[preprocessing]
enabled = true
doc_type = "csv"

[preprocessing.extra]
id_column = "id"
text_column = "body"
timestamp_column = "timestamp"

[docprocessing]
enabled = true
batch_size = 5
prefer_gpu_for_coref = false

[corpusprocessing]
enabled = true